---
deployment:
 tasks:
 - export DEPLOYPATH=/home/user/public_html/affordablecanada
 - /bin/cp index.html $DEPLOYPATH
 - /bin/cp data $DEPLOYPATH
 - /bin/cp img $DEPLOYPATH
 - /bin/cp src $DEPLOYPATH